packages:
  - packages/*

catalogs:
  dev:
    '@changesets/cli': ^2.30.0
    '@tofrankie/action': ^0.0.7
    husky: ^9.1.7
    jsonc-parser: ^3.3.1
    lint-staged: ^16.4.0
    npm-run-all2: ^8.0.4
    publint: ^0.3.18
    tsdown: ^0.21.9
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.1.4
  peer:
    '@commitlint/cli': ^20.4.1
    eslint: ^10.2.0
    prettier: ^3.8.3
    stylelint: ^17.6.0
  prod:
    '@angular-eslint/eslint-plugin': ^21.3.1
    '@angular-eslint/eslint-plugin-template': ^21.3.1
    '@angular-eslint/template-parser': ^21.3.1
    '@antfu/eslint-config': ^8.1.1
    '@commitlint/config-conventional': ^20.4.1
    '@eslint-react/eslint-plugin': ^3.0.0
    '@next/eslint-plugin-next': ^16.2.3
    '@prettier/plugin-xml': ^3.4.2
    '@stylistic/stylelint-plugin': ^5.1.0
    '@tofrankie/postcss-wxml': ^0.0.6
    '@tofrankie/prettier-plugin-wxml': 0.0.11
    '@tsconfig/node20': ^20.1.9
    '@tsconfig/strictest': ^2.0.8
    '@tsconfig/vite-react': ^7.0.2
    '@unocss/eslint-plugin': ^66.6.8
    '@vue/tsconfig': ^0.9.0
    deepmerge: ^4.3.1
    defu: ^6.1.7
    eslint-plugin-astro: ^1.7.0
    eslint-plugin-format: ^2.0.1
    eslint-plugin-jsdoc: ^62.9.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react-refresh: ^0.5.2
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.17.0
    find-up-simple: ^1.0.1
    local-pkg: ^1.1.2
    postcss: ^8.5.9
    postcss-html: ^1.8.1
    postcss-scss: ^4.0.9
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-organize-attributes: ^1.0.0
    stylelint-config-html: ^1.1.0
    stylelint-config-recess-order: ^7.7.0
    stylelint-config-standard: ^40.0.0
    stylelint-config-standard-scss: ^17.0.0
    stylelint-config-standard-vue: ^1.0.0
    stylelint-order: ^8.1.1
  types:
    '@commitlint/types': ^20.4.0
    '@types/node': ^25.6.0
