packages:
  - packages/*

catalogs:
  dev:
    '@changesets/cli': ^2.30.0
    '@tofrankie/action': ^0.0.5
    husky: ^9.1.7
    jsonc-parser: ^3.3.1
    lint-staged: ^16.4.0
    npm-run-all2: ^8.0.4
    publint: ^0.3.18
    tsdown: ^0.21.7
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.1.2
  peer:
    '@commitlint/cli': ^20.4.1
    eslint: ^9.39.4
    prettier: ^3.8.1
    stylelint: ^17.6.0
  prod:
    '@antfu/eslint-config': ^7.7.3
    '@commitlint/config-conventional': ^20.4.1
    '@eslint-react/eslint-plugin': ^2.13.0
    '@stylistic/stylelint-plugin': ^5.0.1
    '@tofrankie/postcss-wxml': ^0.0.4
    '@tofrankie/prettier-plugin-wxml': 0.0.11
    '@tsconfig/node20': ^20.1.9
    '@tsconfig/strictest': ^2.0.8
    '@tsconfig/vite-react': ^7.0.2
    '@vue/tsconfig': ^0.9.0
    deepmerge: ^4.3.1
    eslint-plugin-format: ^2.0.1
    eslint-plugin-jsdoc: ^62.8.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.2
    lodash.merge: ^4.6.2
    postcss: ^8.5.6
    postcss-html: ^1.8.1
    postcss-scss: ^4.0.9
    prettier-plugin-organize-attributes: ^1.0.0
    stylelint-config-html: ^1.1.0
    stylelint-config-recess-order: ^7.7.0
    stylelint-config-standard: ^40.0.0
    stylelint-config-standard-scss: ^17.0.0
    stylelint-config-standard-vue: ^1.0.0
    stylelint-order: ^8.1.1
  types:
    '@commitlint/types': ^20.4.0
    '@types/lodash.merge': ^4.6.9
    '@types/node': ^25.5.0
